# Laboratorio 7: Clasificación 🤗

<center><strong>MDS7202: Laboratorio de Programación Científica para Ciencia de Datos - Primavera 2024</strong></center>


### Cuerpo Docente:

- Profesores: Ignacio Meza, Sebastián Tinoco
- Auxiliar: Eduardo Moya
- Ayudantes: Nicolás Ojeda, Melanie Peña, Valentina Rojas

### Equipo: Ratas.py 🐁

- Nombre de alumno 1: Geraldyn Pérez
- Nombre de alumno 2: Diego Rojas

### **Link de repositorio de GitHub:** [Repositorio](https://github.com/Geral37/MDS7202.git)

### Temas a tratar
- Clasificación en problemas desbalanceados
- Lightgbm y xgboost
- Pipelines

### Reglas:

- **Grupos de 2 personas**
- Cualquier duda fuera del horario de clases al foro. Mensajes al equipo docente serán respondidos por este medio.
- Prohibidas las copias.
- Pueden usar cualquer matrial del curso que estimen conveniente.
- Código que no se pueda ejecutar, no será revisado.



### Objetivos principales del laboratorio
- Comprender cómo trabajar con problemas de clasificación con clases desbalanceadas.
- Aplicar los modelos lightgbm y xgboost.
- Practicar Pipelines

# Parte Teórica [12 puntos]




1. Explique cuál es la diferencia entre los datos de entrenamiento y validación. [1 punto]

2. Explique cuál es el principal desafío al trabajar problemas de clasificación con data no supervisada. [1 punto]

3. Explique en **sus palabras** qué es la matriz de confusión y para qué se utiliza. [1 puntos]

4. Escriba la fórmula de las siguientes métricas y explique con **sus palabras** cómo se interpretan. [1 punto cada uno]

  * Accuracy
  * Precision
  * Recall
  * F1 score

5. Explique qué métrica recomendaría para los siguientes contextos de clasificación. [1 punto cada uno]

  * Mantenimiento predictivo de fallas de maquinaria pesada en la industria minera.  
  * Detección de enfermedades altamente contagiosas.
  * Aprobación de créditos de alto riesgo.
  * Detección de crímenes.

6. Explique qué es la calibración de modelos y para qué se usa. [1 punto]


**Respuesta:**

1. Los datos de entrenamiento, son aquellos que se usan para entrenar el modelo, es decir, para ejecutar el algoritmo permitiendo al modelo ajustar sus parámetros óptimos, mientras que los de validación son los que se usan para medir el rendimiento del modelo sin influir en el proceso de aprendizaje de este, dado que la medición se realiza con datos que no han sido vistos por el durante el entrenamiento.

2. El principal desafío es la ausencia de etiquetas, lo que dificulta definir y evaluar clases. Sin referencias conocidas, el modelo debe descubrir patrones por sí mismo, lo que puede llevar a resultados poco interpretables o inexactos.

3. Es una tabla donde se muestra la cantidad de veces que el modelo clasificó ciertas variables según la etiqueta correspondiente, es decir, muestra cuántas veces las predicciones del modelo coinciden con las etiquetas reales y cuántas no.

4. Considerando:

*Verdadero positivo (TP):* Instancias positivas que fueron correctamente clasificadas.

*Verdadero negativo (TN):* Instancias negativas que fueron correctamente clasificadas.

*Falso positivo (FP):* Instancias negativas que fueron incorrectamente clasificadas como positivas.

*Falso negativo (FN):* Instancias positivas que fueron incorrectamente clasificadas negativas.

  * Accuracy: es la proporción del conjunto de prueba que está clasificado correctamente y se calcula como:

$$
\displaystyle \small accuracy = \frac{TP + TN}{TP + FP + TN + FN}
$$

  * Precision: es una medida de la exactitud, o el porcentaje de instancias clasificadas como positivas que realmente lo son y se calcula como:

$$
\displaystyle \small precision = \frac{TP}{TP + FP}
$$

  * Recall: es la proporción de instancias positivas que son clasificadas correctamente y se calcula como:
  
$$
\displaystyle \small recall = \frac{TP}{TP + FN}
$$

  * F1 score: es la combinación entre precision y recall en una solo medida. Esto otorga igual peso a la precisión y la exhaustividad y se calcula como:

$$
\displaystyle \small F_1 = \frac{2\times precision \times recall}{precision + recall}
$$

5.
  * Mantenimiento predictivo de fallas de maquinaria pesada en la industria minera: En este caso, es crucial asegurar que se detecten la mayor cantidad de fallas posibles, con tal de evitar accidentes graves o interrupciones costosas, por lo que lo más adecuado sería utilizar recall.

  * Detección de enfermedades altamente contagiosas: En este caso, nos importa tener la menor cantidad de falsos negativos para controlar la propagación de la enfermedad, por lo que lo más adecuado sería utilizar recall.

  * Aprobación de créditos de alto riesgo: En este caso, nos importa minimizar los falsos positivos, , ya que otorgar un crédito a un solicitante de alto riesgo puede ser costoso para la entidad financiera, por lo que lo más adecuado sería utilizar precision.

  * Detección de crímenes: En este caso, necesitamos mantener un equilibrio entre no perder ningún crimen y no acusar erróneamente a inocentes, por lo que lo más adecuado sería utilizar F1 score.

6. La calibración de modelos es el proceso de ajustar las predicciones de un modelo para que las probabilidades que genera sean más confiables y reflejen la realidad. Esto es importante en modelos de clasificación probabilística, ya que permite que, por ejemplo, si un modelo indica una probabilidad del 70%, esa clase ocurra efectivamente el 70% de las veces. Una buena calibración mejora la interpretación de las predicciones y la toma de decisiones


# Parte práctica [48 puntos]

<p align="center">
  <img src="https://i.ibb.co/61L8z0w/renacin-by-volframio-dcirf4l-fullview.jpg"
" width="400">
</p>



Tras el trágico despido de la mítica mascota de Maipú, Renacín decide adentrarse como consultor en el mercado futbolero, el cuál (para variar...) está cargado en especulaciones.

Como su principal tarea será asesorar a los directivos de los clubes sobre cuál jugador comprar y cuál no, Renacín desea generar modelos predictivos que evaluén distintas características de los jugadores; todo con el fin de tomar decisiones concretas basadas en los datos.

Sin embargo, su condición de corporeo le impidió tomar la versión anterior de MDS7202, por lo que este motivo Renacín contrata a su equipo para lograr su objetivo final. Dado que aún tiene fuertes vínculos con la dirección de deportes de la municipalidad, el corporeo le entrega base de datos con las estadísticas de cada jugador para que su equipo empieze a trabajar ya con un dataset listo para ser usado.


**Los Datos**

Para este laboratorio deberán trabajar con el csv `statsplayers.csv`, donde deberán aplicar algoritmos de aprendizaje supervisado de clasificación en base a características que describen de jugadores de fútbol.

Para comenzar cargue el dataset señalado y a continuación vea el reporte **`Player_Stats_Report.html`** (adjunto en la carpeta del enunciado) que describe las características principales del `DataFrame`.

In [54]:
# Si usted está utilizando Colabolatory le puede ser útil este código para cargar los archivos.
try:
    from google.colab import drive
    drive.mount("/content/drive")
    path = 'Dirección donde tiene los archivos en el Drive'
except:
    print('Ignorando conexión drive-colab')

Ignorando conexión drive-colab


**Librerías necesarias**

In [55]:
import pandas as pd
import numpy as np

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder, FunctionTransformer
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, precision_score, recall_score, classification_report
from sklearn.svm import SVC
from sklearn.preprocessing import LabelEncoder

from lightgbm import LGBMClassifier
from xgboost import XGBClassifier

In [56]:
df = pd.read_csv('stats_players.csv')
df.head()

Name Nationality National_Position Club_Position  Height  \
0  Cristiano Ronaldo    Portugal                LS            LW     185   
1       Lionel Messi   Argentina                RW            RW     170   
2             Neymar      Brazil                LW            LW     174   
3        Luis Suárez     Uruguay                LS            ST     182   
4       Manuel Neuer     Germany                GK            GK     193   

   Weight Preffered_Foot  Age        Work_Rate  Weak_foot  ...  Agility  \
0      80          Right   32       High / Low          4  ...       90   
1      72           Left   29  Medium / Medium          4  ...       90   
2      68          Right   25    High / Medium          5  ...       96   
3      85          Right   30    High / Medium          4  ...       86   
4      92          Right   31  Medium / Medium          4  ...       52   

   Jumping  Heading  Shot_Power  Finishing  Long_Shots  Curve  \
0       95       85          92         93          90     81   
1       68       71          85         95          88     89   
2       61       62          78         89          77     79   
3       69       77          87         94          86     86   
4       78       25          25         13          16     14   

   Freekick_Accuracy  Penalties  Volleys  
0                 76         85       88  
1                 90         74       85  
2                 84         81       83  
3                 84         85       88  
4                 11         47       11  

[5 rows x 39 columns]

## 1. Predicción de Seleccionados Nacionales [14 puntos]

<p align="center">
  <img src="https://www.futuro.cl/wp-content/uploads/2016/06/chile-argentina-meme-12.jpg" width="300">
</p>



### 1.1 Preprocesamiento [5 puntos]

Tareas:

1. Genere los labels para la clasificación binaria en una variable llamada `label`. Para esto, trabaje sobre el atributo `National_Position` suponiendo que los valores nulos son jugadores no seleccionados para representar a su país. [Sin puntaje]

2. Hecho esto, ¿cuántos se tienen ejemplos por cada clase? Comente lo que observa. [1 punto]

3. Genere un `ColumnTransformer` en donde especifique las transformaciones que hay que realizar para cada columna (por ejemplo StandarScaler, MinMaxScaler, OneHotEncoder, etc...) para que puedan ser utilizadas correctamente por el modelo predictivo y guárdelo una variable llamada `col_transformer`. [2 puntos]

4. Comente y justifique las transformaciones elegidas sobre cada una de las variables (para esto utilice el material `Player_Stats_Report.html` que viene en el zip del lab), al igual que las transformaciones aplicadas. [2 puntos]

**Respuesta:**

In [57]:
#1. Genere los labels para la clasificación binaria en una variable llamada `label`.
df['label'] = df['National_Position'].notnull().astype(int)

#2. Ejemplos por cada clase
clases = df['label'].value_counts()
print(clases)

label
0    16513
1     1075
Name: count, dtype: int64


2. Se puede observar que hay 1.075 jugadores que son seleccionados para representar a su país y hay 16.513 jugadores que no lo son. Por lo que, solo aprox. el 6% corresponde a seleccionados.

In [58]:
df.dtypes

Name                 object
Nationality          object
National_Position    object
Club_Position        object
Height                int64
Weight                int64
Preffered_Foot       object
Age                   int64
Work_Rate            object
Weak_foot             int64
Skill_Moves           int64
Ball_Control          int64
Dribbling             int64
Marking               int64
Sliding_Tackle        int64
Standing_Tackle       int64
Aggression            int64
Reactions             int64
Interceptions         int64
Vision                int64
Composure             int64
Crossing              int64
Short_Pass            int64
Long_Pass             int64
Acceleration          int64
Speed                 int64
Stamina               int64
Strength              int64
Balance               int64
Agility               int64
Jumping               int64
Heading               int64
Shot_Power            int64
Finishing             int64
Long_Shots            int64
Curve                 int64
Freekick_Accuracy     int64
Penalties             int64
Volleys               int64
label                 int64
dtype: object

In [59]:
variables_numericas = df.select_dtypes(include=['number']).columns.tolist()

variables_categoricas = df.select_dtypes(include=['object']).columns.tolist()

print("Variables numéricas:", variables_numericas)
print("Variables categóricas:", variables_categoricas)

Variables numéricas: ['Height', 'Weight', 'Age', 'Weak_foot', 'Skill_Moves', 'Ball_Control', 'Dribbling', 'Marking', 'Sliding_Tackle', 'Standing_Tackle', 'Aggression', 'Reactions', 'Interceptions', 'Vision', 'Composure', 'Crossing', 'Short_Pass', 'Long_Pass', 'Acceleration', 'Speed', 'Stamina', 'Strength', 'Balance', 'Agility', 'Jumping', 'Heading', 'Shot_Power', 'Finishing', 'Long_Shots', 'Curve', 'Freekick_Accuracy', 'Penalties', 'Volleys', 'label']
Variables categóricas: ['Name', 'Nationality', 'National_Position', 'Club_Position', 'Preffered_Foot', 'Work_Rate']


In [60]:
variables_categoricas

['Name',
 'Nationality',
 'National_Position',
 'Club_Position',
 'Preffered_Foot',
 'Work_Rate']

In [61]:
#3. Genere un `ColumnTransformer`
variables_numericas1 = ['Height', 'Weight', 'Age', 'Weak_foot', 'Skill_Moves']

variables_numericas2 = ['Ball_Control', 'Dribbling', 'Marking', 'Sliding_Tackle', 'Standing_Tackle',
                        'Aggression', 'Reactions', 'Interceptions', 'Vision', 'Composure', 'Crossing',
                        'Short_Pass', 'Long_Pass', 'Acceleration', 'Speed', 'Stamina', 'Strength',
                        'Balance', 'Agility', 'Jumping', 'Heading', 'Shot_Power', 'Finishing',
                        'Long_Shots', 'Curve', 'Freekick_Accuracy', 'Penalties', 'Volleys']

variables_categoricas = ['Preffered_Foot', 'Work_Rate']

# Crear una función que divida por 100
def dividir_por_100(X):
    return X / 100

col_transformer = ColumnTransformer(
    transformers=[
        ('num_div_100', FunctionTransformer(dividir_por_100), variables_numericas1),  # Dividir los valores entre 100 para variables que van hasta 100
        ('num_minmax', MinMaxScaler(), variables_numericas2),  # MinMaxScaler para variables numéricas generales
        ('cat', OneHotEncoder(handle_unknown='ignore'), variables_categoricas)  # OneHotEncoder para categóricas
    ]
)

print(col_transformer)

ColumnTransformer(n_jobs=None, remainder='drop', sparse_threshold=0.3,
                  transformer_weights=None,
                  transformers=[('num_div_100',
                                 FunctionTransformer(accept_sparse=False,
                                                     check_inverse=True,
                                                     feature_names_out=None,
                                                     func=<function dividir_por_100 at 0x7a24335e7130>,
                                                     inv_kw_args=None,
                                                     inverse_func=None,
                                                     kw_args=None,
                                                     validate=False),
                                 ['Height', 'Weight', 'Age', 'Weak_foot...
                                  'Agility', 'Jumping', 'Heading', 'Shot_Power',
                                  'Finishing', 'Long_Shots', 'Curve',
   

4.

Existe una gran cantidad de variables numéricas y algunas categóricas. Las numéricas pueden ser agrupadas en 2 conjuntos:

- Características del jugador
- Estadísticas de habilidades

El primer conjunto varía su dominio para cada variable, mientras que el segundo está acotado entre 0 y 100.

Así, se dividen las columnas en 3 grupos y se aplica una transformación distinta para cada uno. Al primer conjunto, dado que no tienen un dominio constante entre ellas, se les aplica MinMaxScaler, mientras que al segundo se le aplica MinMaxScaler pero de manera personalizada pero con el rango fijo entre 0 y 100, utilizando una función que considera que el máximo valor posible es 100.


### **( o usamos MinMax para todo no mas?)**
Mejor si

In [62]:
#3. Genere un `ColumnTransformer`

col_transformer2 = ColumnTransformer(
    transformers=[
        ('num_minmax100', MinMaxScaler(feature_range=(0, 100)), variables_numericas2),  # MinMaxScaler para variables numéricas asociadas a estadísticas
        ('num_minmax', MinMaxScaler(), variables_numericas1),  # ahora para las otras
        ('cat', OneHotEncoder(handle_unknown='ignore'), variables_categoricas)  # OneHotEncoder para categóricas
    ]
)

print(col_transformer2)

ColumnTransformer(n_jobs=None, remainder='drop', sparse_threshold=0.3,
                  transformer_weights=None,
                  transformers=[('num_minmax100',
                                 MinMaxScaler(clip=False, copy=True,
                                              feature_range=(0, 100)),
                                 ['Ball_Control', 'Dribbling', 'Marking',
                                  'Sliding_Tackle', 'Standing_Tackle',
                                  'Aggression', 'Reactions', 'Interceptions',
                                  'Vision', 'Composure', 'Crossing',
                                  'Short_Pass', 'Long_Pass...
                                 MinMaxScaler(clip=False, copy=True,
                                              feature_range=(0, 1)),
                                 ['Height', 'Weight', 'Age', 'Weak_foot',
                                  'Skill_Moves']),
                                ('cat',
                                 OneHo

### 1.2 Entrenamiento [3 puntos]

Ahora, vamos a entrenar los pipelines generados en los pasos anteriores. Para esto, debe realizar las siguientes tareas:

1. Separe los datos de entrenamiento en un conjunto de entrenamiento y de prueba  (la proporción queda a su juicio). En este paso, seleccione los ejemplos de forma aleatoria e intente mantener la distribución original de labels de cada clase en los conjuntos de prueba/entrenamiento. (vea la documentación de `train_test_split`). [1 puntos]


2. Defina un pipeline llamado `pipeline_xgboost` y otro llamado `pipeline_lightgbm`. Estos pipelines deben tener el mismo ColumnTransformer definido en la sección de preprocesamiento, pero deben variar los clasificadores de acuerdo al nombre de cada pipeline. [1 puntos]

3. Entrene los pipelines. [1 punto]



**Respuesta:**

In [63]:
df.columns

Index(['Name', 'Nationality', 'National_Position', 'Club_Position', 'Height',
       'Weight', 'Preffered_Foot', 'Age', 'Work_Rate', 'Weak_foot',
       'Skill_Moves', 'Ball_Control', 'Dribbling', 'Marking', 'Sliding_Tackle',
       'Standing_Tackle', 'Aggression', 'Reactions', 'Interceptions', 'Vision',
       'Composure', 'Crossing', 'Short_Pass', 'Long_Pass', 'Acceleration',
       'Speed', 'Stamina', 'Strength', 'Balance', 'Agility', 'Jumping',
       'Heading', 'Shot_Power', 'Finishing', 'Long_Shots', 'Curve',
       'Freekick_Accuracy', 'Penalties', 'Volleys', 'label'],
      dtype='object')

In [64]:
# 1

# Separar las características (X) y las etiquetas (y)
X = df.drop(columns=['label', 'Name', 'Nationality', 'National_Position'])
#X = df.drop(columns=['label'])
y = df['label']

# División de datos en entrenamiento y prueba, estratificando por la variable 'label'
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=33, stratify=y)

# Verificar la forma de los conjuntos
print("Conjunto de entrenamiento:", X_train.shape)
print("Conjunto de prueba:", X_test.shape)


Conjunto de entrenamiento: (12311, 36)
Conjunto de prueba: (5277, 36)


In [65]:
#2

# Pipeline para XGBoost
pipeline_xgboost = Pipeline(steps=[
    ('preprocessor', col_transformer),
    ('classifier', XGBClassifier(random_state=33))
])

# Pipeline para LightGBM
pipeline_lightgbm = Pipeline(steps=[
    ('preprocessor', col_transformer),
    ('classifier', LGBMClassifier(random_state=33))
])

In [66]:
# Entrenar el pipeline de XGBoost
pipeline_xgboost.fit(X_train, y_train)

# Entrenar el pipeline de LightGBM
pipeline_lightgbm.fit(X_train, y_train)

# Verificar la finalización del entrenamiento
print("Entrenamiento completado para ambos modelos.")

[LightGBM] [Info] Number of positive: 752, number of negative: 11559
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003101 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2450
[LightGBM] [Info] Number of data points in the train set: 12311, number of used features: 43
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.061084 -> initscore=-2.732483
[LightGBM] [Info] Start training from score -2.732483
Entrenamiento completado para ambos modelos.


### 1.3 Resultados [6 puntos]

1. Calcule las métricas accuracy, precisión y recall de la clase positiva (la que indica que un jugador es seleccionado nacional) para evaluar el rendimiento de los distintos modelos. Verifique sus resultados usando `classification_report`. [2 puntos]

2. Explique qué implican los valores de accuracy, precisión y recall de la clase positiva (la que indica que un jugador es seleccionado nacional) y cómo influye la cantidad de ejemplos por clase en los resultados obtenidos. [2 puntos]

3. Explique qué métrica le parece más adecuada y concluya qué modelo tiene un mejor desempeño. [2 puntos]

**Respuesta:**

In [67]:
# Predicciones con XGBoost
y_pred_xgboost = pipeline_xgboost.predict(X_test)

# Predicciones con LightGBM
y_pred_lightgbm = pipeline_lightgbm.predict(X_test)

# Calcular las métricas para XGBoost
accuracy_xgboost = accuracy_score(y_test, y_pred_xgboost)
precision_xgboost = precision_score(y_test, y_pred_xgboost)
recall_xgboost = recall_score(y_test, y_pred_xgboost)

# Calcular las métricas para LightGBM
accuracy_lightgbm = accuracy_score(y_test, y_pred_lightgbm)
precision_lightgbm = precision_score(y_test, y_pred_lightgbm)
recall_lightgbm = recall_score(y_test, y_pred_lightgbm)

# Mostrar resultados
print(f"XGBoost - Accuracy: {accuracy_xgboost:.4f}, Precision: {precision_xgboost:.4f}, Recall: {recall_xgboost:.4f}")
print(f"LightGBM - Accuracy: {accuracy_lightgbm:.4f}, Precision: {precision_lightgbm:.4f}, Recall: {recall_lightgbm:.4f}")

XGBoost - Accuracy: 0.9377, Precision: 0.4651, Recall: 0.1238
LightGBM - Accuracy: 0.9399, Precision: 0.5417, Recall: 0.1207


In [68]:
# Generar el informe de clasificación para XGBoost
print("XGBoost Classification Report:")
print(classification_report(y_test, y_pred_xgboost, target_names=['No Seleccionado', 'Seleccionado Nacional']))

# Generar el informe de clasificación para LightGBM
print("LightGBM Classification Report:")
print(classification_report(y_test, y_pred_lightgbm, target_names=['No Seleccionado', 'Seleccionado Nacional']))

XGBoost Classification Report:
                       precision    recall  f1-score   support

      No Seleccionado       0.95      0.99      0.97      4954
Seleccionado Nacional       0.47      0.12      0.20       323

             accuracy                           0.94      5277
            macro avg       0.71      0.56      0.58      5277
         weighted avg       0.92      0.94      0.92      5277

LightGBM Classification Report:
                       precision    recall  f1-score   support

      No Seleccionado       0.95      0.99      0.97      4954
Seleccionado Nacional       0.54      0.12      0.20       323

             accuracy                           0.94      5277
            macro avg       0.74      0.56      0.58      5277
         weighted avg       0.92      0.94      0.92      5277



2.  
En el caso de XGBoost, la precision es de 0.47, lo que significa que, de todas las predicciones de "Seleccionado Nacional", solo el 47% fueron correctas. Esto sugiere un alto número de falsos positivos, lo que indica que el modelo tiende a clasificar incorrectamente a jugadores que no son realmente seleccionados. El recall, con un valor de 0.12, indica que de todos los jugadores que realmente son "Seleccionados Nacionales", solo el 12% fue identificado correctamente. Este bajo valor implica que el modelo enfrenta dificultades significativas para detectar a los jugadores seleccionados, lo que puede ser problemático en un contexto donde es crucial identificar positivos. La F1-score de 0.20 refuerza la idea de que el modelo tiene un rendimiento deficiente al no lograr un equilibrio adecuado entre precisión y recall. Este análisis  es equivalente para el caso de LightGBM.

En ambos modelos hay 4954 ejemplos de la clase "No Seleccionado" y 323 ejemplos de la clase "Seleccionado Nacional". Esto muestra un desbalance significativo entre las dos clases, ya que la clase "Seleccionado Nacional" representa solo alrededor del 6% del total de ejemplos.

Ambos modelos presentan una accuracy de 0.94 (94%), lo que implica que, en general, el 94% de las predicciones son correctas. La alta accuracy se debe principalmente a la gran cantidad de ejemplos de la clase mayoritaria ("No Seleccionado"). Esto significa que, aunque los modelos están acertando la mayoría de las predicciones, este éxito se debe a que están clasificando correctamente la clase mayoritaria, mientras que las predicciones de la clase minoritaria son deficientes.

3.#
 En general LightGBM tiene mejor rendimiento. Entrega mejor Accuracy, acertando a gran cantidad de las etiquetas, y también mejor Precisión, entregando menos falsos positivos, pero ambos tienen bajo Recall, dejando fuera muchos positivos. La más adecuada sería recall (o precisión), para capturar la mayor cantidad de posibles seleccionados, ya que es mejor considerar a un jugador como seleccionado y al final que no sea considerado, por sobre dejar pasar la oportunidad de seleccionar a un buen jugador.

La más adecuada sería recall (o precisión), para capturar la mayor cantidad de posibles seleccionados, ya que es mejor considerar a un jugador como seleccionado y al final que no sea considerado, por sobre dejar pasar la oportunidad de seleccionar a un buen jugador. En general, LightGBM y XGBoost tienen rendimientos similares. LightGBM tiene mejor Precisión, entregando menos falsos positivos, por lo que este modelo tendría el mejor desempeño.

Quité la posición y cambió lo del recall. lo dejamos?

## 2. Predicción de posiciones de jugadores [4 puntos]

<p align="center">
  <img src="https://pbs.twimg.com/media/E1rfA1aWEAYU6Ny.jpg" width="300">
</p>

En una nueva jornada de desmesuradas transacciones deportivas, Renacín escuchó a sus colegas discutir acerca de que el precio de cada jugador depende en gran medida de la posición en la cancha en la que juega. Y además, que hay bastantes jugadores nuevos que no tienen muy claro en que posición verdaderamente brillarían, por lo que actualmente puede que actualmente estén jugando en posiciones sub-optimas.

Viendo que los resultados del primer análisis no son tan esperanzadores, el corporeo los comanda a cambiar su tarea: ahora, les solicita que construyan un clasificador enfocado en predecir la mejor posición de los jugadores en la cancha según sus características.

Para lograr esto, primero, les pide que etiqueten de la siguiente manera los valores que aparecen en el atributo `Club_Position`, pidiendo que agrupen los valores en los siguientes grupos:

**Nota**:  Renacín les recalca que **no deben utilizar los valores ```Sub``` y ```Res``` de esta columna**.

```python
ataque = ['ST', 'CF']
central_ataque = ['RW', 'CAM', 'LW']
central = ['RM', 'CM', 'LM']
central_defensa = ['RWB', 'CDM', 'LWB']
defensa = ['RB', 'CB', 'LB']
arquero = ['GK']
```

La elección del clasificador se justificar en base a la siguiente [guía](https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html) y se deben comentar los resultados obtenidos en la clasificación.

**Tareas:** [1 punto por tarea]

1. En un nuevo dataframe, aplique las etiquetas descritas anteriormente en cada uno de los valores señalados en esta sección y guárdelos en la variable `label`.
2. Cuente cuántos por clase quedan.
3. Entrene el nuevo pipeline y ejecute una evaluación de este.  
4. Comente los resultados obtenidos.

**Respuesta:**

In [69]:
# Función para etiquetar las posiciones
def label_positions(position):
    if position in ['ST', 'CF']:
        return 'ataque'
    elif position in ['RW', 'CAM', 'LW']:
        return 'central_ataque'
    elif position in ['RM', 'CM', 'LM']:
        return 'central'
    elif position in ['RWB', 'CDM', 'LWB']:
        return 'central_defensa'
    elif position in ['RB', 'CB', 'LB']:
        return 'defensa'
    elif position == 'GK':
        return 'arquero'
    else:
        return None  # Excluimos las posiciones 'Sub' y 'Res'

df['label_pos'] = df['Club_Position'].apply(label_positions)

df = df[df['label_pos'].notna()]

class_counts = df['label_pos'].value_counts()
class_counts

label_pos
defensa            1180
central             907
arquero             632
central_ataque      581
ataque              430
central_defensa     209
Name: count, dtype: int64

In [70]:
df.columns

Index(['Name', 'Nationality', 'National_Position', 'Club_Position', 'Height',
       'Weight', 'Preffered_Foot', 'Age', 'Work_Rate', 'Weak_foot',
       'Skill_Moves', 'Ball_Control', 'Dribbling', 'Marking', 'Sliding_Tackle',
       'Standing_Tackle', 'Aggression', 'Reactions', 'Interceptions', 'Vision',
       'Composure', 'Crossing', 'Short_Pass', 'Long_Pass', 'Acceleration',
       'Speed', 'Stamina', 'Strength', 'Balance', 'Agility', 'Jumping',
       'Heading', 'Shot_Power', 'Finishing', 'Long_Shots', 'Curve',
       'Freekick_Accuracy', 'Penalties', 'Volleys', 'label', 'label_pos'],
      dtype='object')

Por lo de la guía debería ser SVC?

In [71]:
X = df.drop(columns=['Club_Position', 'label', 'label_pos'])
y = df['label_pos']

# Codificar las etiquetas
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)  # Esto transformará las etiquetas a valores numéricos

# Separar los datos en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, stratify=y_encoded, random_state=42)

# Definir el nuevo pipeline
pipeline_new = Pipeline(steps=[
    ('preprocessor', col_transformer),  # Reutilizamos el ColumnTransformer anterior
    ('classifier', SVC())
])

# Entrenar el pipeline
pipeline_new.fit(X_train, y_train)

# Realizar predicciones
y_pred = pipeline_new.predict(X_test)

# Evaluar el rendimiento
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.4f}')

# Mostrar el reporte de clasificación
report = classification_report(y_test, y_pred, target_names=label_encoder.classes_)
print(report)

Accuracy: 0.7348
                 precision    recall  f1-score   support

        arquero       1.00      1.00      1.00       126
         ataque       0.80      0.83      0.81        86
        central       0.54      0.75      0.63       182
 central_ataque       0.50      0.12      0.19       116
central_defensa       1.00      0.05      0.09        42
        defensa       0.79      0.97      0.87       236

       accuracy                           0.73       788
      macro avg       0.77      0.62      0.60       788
   weighted avg       0.73      0.73      0.69       788



Da ahí no mas, probemos con LGBM.

In [72]:
X = df.drop(columns=['Club_Position', 'label', 'label_pos'])
y = df['label_pos']

# Codificar las etiquetas
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)  # Esto transformará las etiquetas a valores numéricos

# Separar los datos en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, stratify=y_encoded, random_state=42)

# Definir el nuevo pipeline
pipeline_new = Pipeline(steps=[
    ('preprocessor', col_transformer),  # Reutilizamos el ColumnTransformer anterior
    ('classifier', LGBMClassifier())  #
])

# Entrenar el pipeline
pipeline_new.fit(X_train, y_train)

# Realizar predicciones
y_pred = pipeline_new.predict(X_test)

# Evaluar el rendimiento
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.4f}')

# Mostrar el reporte de clasificación
report = classification_report(y_test, y_pred, target_names=label_encoder.classes_)
print(report)

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005226 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2327
[LightGBM] [Info] Number of data points in the train set: 3151, number of used features: 43
[LightGBM] [Info] Start training from score -1.828938
[LightGBM] [Info] Start training from score -2.214833
[LightGBM] [Info] Start training from score -1.469303
[LightGBM] [Info] Start training from score -1.913438
[LightGBM] [Info] Start training from score -2.937481
[LightGBM] [Info] Start training from score -1.205349
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Accuracy: 0.7360
       

sfgfdg

## 3. Predicciones de Seleccionados Nacionales para el Jere Klein [30 puntos]

<center>
<img src='https://www.radioactiva.cl/wp-content/uploads/2024/04/Jere-Klein-1-768x432.webp' width=500 />

Después de alcanzar la fama como cantante urbano, Jere Klein decide explorar una nueva faceta. Con su amor por el fútbol y convencido de que los artistas urbanos poseen un talento y versatilidad excepcionales, Jere se embarca en un proyecto innovador: desarrollar un sistema de inteligencia artificial capaz de identificar a jugadores que tienen potencial para convertirse en futbolistas profesionales. Su teoría es que muchos artistas del género urbano chileno, con sus habilidades únicas y su disciplina, podrían destacarse también en el deporte. Con este sistema, Jere espera no solo abrir nuevas oportunidades para sus colegas artistas, sino también demostrar la amplia gama de talentos que pueden ofrecer.

### 3.1 ¿Qué modelo de árbol es más de "pana"? [10 puntos]

<center>
<img src='https://64.media.tumblr.com/39189215a7d3d96823cb359f35b44e05/tumblr_psmrhrR3Xw1qf5hjqo4_540.gif' width=300 />


**Tareas**


1. Considerando el la variable llamada `label` creada en la sección 1.1. Para determinar cuál modelo de árbol sería más adecuado para la tarea en cuestión, utilice PyCaret. Este deberá centrarse exclusivamente en modelos de tipo árbol. Jere ha especificado que busca un modelo que tome decisiones rápidamente y que tenga una baja tasa de falsos positivos, ya que planea invertir en estos jugadores. [3 puntos]

Para la comparación, utilice los siguientes modelos:

```python
['et', 'rf', 'dt', 'xgboost', 'lightgbm', 'catboost']
```

2. Explique en brevemente que son los modelos de la siguiente lista `['et', 'rf', 'dt']` y como funcionan. [3 punto]

3. Tras realizar la comparación de modelos, seleccione aquel que muestre el mejor rendimiento en términos de velocidad y precisión, especialmente en la reducción de falsos positivos. Utilice la función `evaluate_model` de PyCaret para revisar y analizar los resultados obtenidos en los siguientes aspectos:

  - **Confusión Matrix**: ¿Cómo se encuentran la tasa de verdaderos positivos y verdaderos negativos?
  - **Threshold**: ¿Es acaso el umbral por defecto del modelo el mejor para las predicciones?
  - **Feature Importance**: ¿Cuáles son las variables con mejor desempeño? ¿A qué podría deberse esto?
  - **Learning Curve**: ¿El modelo presenta algún problema?

  [4 puntos]

**Respuesta**

In [73]:
df.columns

Index(['Name', 'Nationality', 'National_Position', 'Club_Position', 'Height',
       'Weight', 'Preffered_Foot', 'Age', 'Work_Rate', 'Weak_foot',
       'Skill_Moves', 'Ball_Control', 'Dribbling', 'Marking', 'Sliding_Tackle',
       'Standing_Tackle', 'Aggression', 'Reactions', 'Interceptions', 'Vision',
       'Composure', 'Crossing', 'Short_Pass', 'Long_Pass', 'Acceleration',
       'Speed', 'Stamina', 'Strength', 'Balance', 'Agility', 'Jumping',
       'Heading', 'Shot_Power', 'Finishing', 'Long_Shots', 'Curve',
       'Freekick_Accuracy', 'Penalties', 'Volleys', 'label', 'label_pos'],
      dtype='object')

In [74]:
pip install pycaret

In [75]:
pip install catboost

In [87]:
from pycaret.datasets import get_data
from pycaret.classification import *
import os

os.environ["PYCARET_CUSTOM_LOGGING_LEVEL"] = "CRITICAL"

#Continuar código aquí

#df = df.drop(columns=['Club_Position'])  # o ya no

# Iniciar el entorno de PyCaret
clf = setup(data=df, target='label', session_id=7, fold_shuffle=True,
             ignore_features=['Name', 'Nationality', 'National_Position', 'label_pos'])

model_comparison = compare_models(include=['et', 'rf', 'dt', 'xgboost', 'lightgbm', 'catboost'])

best_model = model_comparison

evaluate_model(best_model)

Processing:   0%|          | 0/29 [00:00<?, ?it/s]

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

2.
* Arboles de decisión (dt):  es un modelo de aprendizaje supervisado que organiza los datos en una estructura de árbol, donde cada nodo corresponde a una característica del conjunto de datos y cada rama representa una decisión o regla basada en el valor de esa característica. El objetivo es dividir los datos de manera que se maximice la ganancia de información o se minimice la impureza (entropía o Gini). Este proceso continúa hasta que se alcanza un criterio de parada, como un número mínimo de muestras en un nodo o una máxima profundidad del árbol.

* Random Forest (rf): es un modelo que crea múltiples árboles de decisión en paralelo, cada árbol se entrena con un subconjunto aleatorio de los datos de entrenamiento, y en cada nodo, se selecciona aleatoriamente un subconjunto de características para determinar la mejor división. La predicción final del Random Forest se obtiene mediante el promedio (para regresión) o el voto mayoritario (para clasificación) de todos los árboles.

* Extra Tress (et): es un modelo similar a Random Forest, pero con una mayor aleatoriedad en el proceso de construcción de los árboles. Al igual que en Random Forest, se construyen múltiples árboles de decisión en paralelo utilizando subconjuntos aleatorios de los datos de entrenamiento. Sin embargo, la diferencia clave es que en lugar de buscar la mejor división en cada nodo, Extra Trees elige las divisiones de manera completamente aleatoria.

In [91]:
from pycaret.datasets import get_data
from pycaret.classification import *
import os
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.impute import SimpleImputer

# Suprimir mensajes de log de PyCaret
os.environ["PYCARET_CUSTOM_LOGGING_LEVEL"] = "CRITICAL"

# Aquí puedes cargar tu dataset
# df = get_data('your_data')  # o usar tu propio dataframe df



# Crear transformador de columnas (preprocesamiento)
col_transformer = ColumnTransformer(
    transformers=[
        ('num', Pipeline(steps=[
            ('imputer', SimpleImputer(strategy='mean')),
            ('scaler', StandardScaler())]), numeric_features),
        ('cat', Pipeline(steps=[
            ('imputer', SimpleImputer(strategy='most_frequent')),
            ('onehot', OneHotEncoder(handle_unknown='ignore'))]), categorical_features)
    ]
)

# Definir tus pipelines personalizados
pipeline = Pipeline(steps=[
    ('preprocessor', col_transformer),
    ('classifier', SVC(random_state=33))
])

# Dividir datos antes de PyCaret
X = df.drop('label', axis=1)
y = df['label']

# Configurar las columnas que deseas preprocesar
numeric_features = X.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_features = X.select_dtypes(include=['object']).columns.tolist()

# Entrenar y preprocesar usando el pipeline externo
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=33)

# Aplicar pipelines a los datos de entrenamiento y prueba
pipeline.fit(X_train, y_train)

# Obtener predicciones
predictions = pipeline.predict(X_test)

# Pasar datos preprocesados a PyCaret
df_processed = pd.concat([pd.DataFrame(X_train), pd.DataFrame(y_train)], axis=1)

# Iniciar el entorno de PyCaret con los datos preprocesados
clf = setup(data=df_processed, target='label', session_id=7, fold_shuffle=True,
             ignore_features=['Name', 'Nationality', 'National_Position', 'label_pos'])

# Compara modelos en PyCaret
model_comparison = compare_models(include=['et', 'rf', 'dt', 'xgboost', 'lightgbm', 'catboost'])

# Seleccionar el mejor modelo
best_model = model_comparison

# Evaluar el mejor modelo
evaluate_model(best_model)

ValueError: A given column is not a column of the dataframe

### 3.2 Reducción de dimensionalidad [14 puntos]

<center>
<img src='https://i.kym-cdn.com/photos/images/original/002/258/560/668.gif' width=400 />

A pesar de los resultados obtenidos previamente, el manager de Jere ha solicitado el entrenamiento de un modelo de XGBoost utilizando los datos disponibles. Además, se debe proceder a realizar una reducción de dimensionalidad basada en la importancia de las características.

Para llevar a cabo esta tarea:

1. Inicie entrenando un modelo XGBoost con todas las características disponibles. [2 puntos]

2. Una vez el modelo esté entrenado, evalúe y clasifique las características según su importancia de forma descendente. [2 puntos]

3. Utilice esta clasificación para ejecutar una búsqueda recursiva de eliminación de características, eliminando progresivamente las menos importantes y evaluando el impacto en el desempeño del modelo hasta identificar las N características más críticas. [2 puntos]

4. Con este conjunto reducido de características, entrene un nuevo modelo y evalúe su rendimiento. [2 puntos]

5. Posteriormente, responda a las siguientes preguntas para una comprensión más profunda de los cambios y beneficios:

  - ¿El rendimiento del modelo con las características seleccionadas es similar al del modelo original? ¿Cómo se comparan en términos de precisión y robustez? [2 puntos]
  - ¿Cuáles son los beneficios potenciales de eliminar variables del modelo? Considere factores como la simplificación del modelo, reducción del tiempo de entrenamiento, y mejora en la capacidad de generalización. [2 puntos]
  - Comente si el modelo con menor dimensionalidad es más sencillo de explicar. Explique brevemente por qué la eliminación de ciertas características puede facilitar la comprensión y la explicación del comportamiento del modelo. [2 puntos]

Notar que con esta metodologia buscamos encontrar un punto entermedio entre número de festures y desempeño. por esto, si observa que al aumentar festires el aumento es despreciable, puede no considerar agregar más features a su modelo.

**Respuesta**

Entrenar con todas las disponibles despues de creadas? o disponibles desde el comienzo?

In [77]:
# Iniciar el entorno de PyCaret
clf = setup(data=df, target='label', session_id=7, fold_shuffle=True,
             ignore_features=['Name', 'Nationality', 'National_Position'])

xgb_model = create_model('xgboost')

evaluate_model(xgb_model)

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [78]:
X_train = get_config('X_train')  # Obtener el conjunto de entrenamiento
feature_names = X_train.columns.tolist()  # Nombres de las características
importance_values = xgb_model.feature_importances_  # Importancia de las características

print(f'Longitud de características: {len(feature_names)}')
print(f'Longitud de importancias: {len(importance_values)}')

if len(feature_names) != len(importance_values):
    print("Longitudes no coinciden. Comparando las listas:")
    print("Características:", feature_names)
    print("Importancias:", importance_values)

feature_importance = pd.DataFrame({
    'Feature': feature_names,
    'Importance': importance_values[:len(feature_names)]  # Alinear
})

feature_importance = feature_importance[feature_importance['Importance'] > 0]
feature_importance = feature_importance.sort_values(by='Importance', ascending=False)

feature_importance

Longitud de características: 37
Longitud de importancias: 64
Longitudes no coinciden. Comparando las listas:
Características: ['Club_Position', 'Height', 'Weight', 'Preffered_Foot', 'Age', 'Work_Rate', 'Weak_foot', 'Skill_Moves', 'Ball_Control', 'Dribbling', 'Marking', 'Sliding_Tackle', 'Standing_Tackle', 'Aggression', 'Reactions', 'Interceptions', 'Vision', 'Composure', 'Crossing', 'Short_Pass', 'Long_Pass', 'Acceleration', 'Speed', 'Stamina', 'Strength', 'Balance', 'Agility', 'Jumping', 'Heading', 'Shot_Power', 'Finishing', 'Long_Shots', 'Curve', 'Freekick_Accuracy', 'Penalties', 'Volleys', 'label_pos']
Importancias: [0.         0.010302   0.00885079 0.         0.         0.01524809
 0.         0.01448886 0.00318253 0.         0.01298278 0.
 0.         0.         0.         0.02141181 0.01807959 0.01844441
 0.02781842 0.01127954 0.01850824 0.         0.         0.02442102
 0.04389    0.0050773  0.         0.         0.01559238 0.02976951
 0.02636902 0.03387395 0.02274314 0.01333847 0

Feature  Importance
36          label_pos    0.124333
24           Strength    0.043890
31         Long_Shots    0.033874
29         Shot_Power    0.029770
18           Crossing    0.027818
30          Finishing    0.026369
23            Stamina    0.024421
32              Curve    0.022743
34          Penalties    0.021674
15      Interceptions    0.021412
20          Long_Pass    0.018508
17          Composure    0.018444
35            Volleys    0.018092
16             Vision    0.018080
28            Heading    0.015592
5           Work_Rate    0.015248
7         Skill_Moves    0.014489
33  Freekick_Accuracy    0.013338
10            Marking    0.012983
19         Short_Pass    0.011280
1              Height    0.010302
2              Weight    0.008851
25            Balance    0.005077
8        Ball_Control    0.003183

In [ ]:
y_train = get_config('y')  # Obtener la variable objetivo
non=['Name', 'Nationality', 'National_Position']
# Inicializar la lista de características
feature_names = X_train.columns.tolist()
N = 1
# Búsqueda recursiva de eliminación de características
while len(feature_names) > N:
    # Obtener la importancia de las características
    importance_values = xgb_model.feature_importances_

    # Crear un DataFrame de importancia de características
    feature_importance = pd.DataFrame({
        'Feature': feature_names,
        'Importance': importance_values[:len(feature_names)]
    })

    # Filtrar las características menos importantes
    feature_importance = feature_importance.sort_values(by='Importance')
    least_important_feature = feature_importance.iloc[0]['Feature']  # Obtener la característica menos importante

    # Eliminar la característica menos importante del conjunto de características
    feature_names.remove(least_important_feature)
    print(f'Eliminando característica: {least_important_feature}')
    non.append(least_important_feature)

    # Reentrenar el modelo con el nuevo conjunto de características
    clf = setup(data=df, target='label', session_id=7, fold_shuffle=True,
             ignore_features=non)

    xgb_model = create_model('xgboost')

    # Evaluar el rendimiento del modelo
    evaluate_model(xgb_model)

importance_values = xgb_model.feature_importances_
feature_importance = pd.DataFrame({
        'Feature': feature_names,
        'Importance': importance_values[:len(feature_names)]
})
feature_importance

Viendo como va progresando el modelo a medida que se le van agregando features (es decir, viendo los resultados de abajo hacia arriba) se decide tomar un N = 5, ya que al tener N = 6 la mayoria de los valores promedio de las medidas disminuye en vez de aumentar. Por lo tanto, se conservarán las siguientes columnas ['Weak_foot', 'Age','Preffered_Foot', 'Weight', 'Work_Rate'].

Otro intento

Malo

In [84]:
from pycaret.classification import *
from sklearn.metrics import accuracy_score, recall_score, f1_score, precision_score
import pandas as pd
import numpy as np

def create_detailed_selection_process(df, target='label'):
    # Obtener todas las características originales
    all_features = [col for col in df.columns if col != target]
    ignored_features_initial = ['Name', 'Nationality', 'National_Position', 'label_pos']

    # Configuración inicial (con ajuste de clases desbalanceadas)
    clf = setup(data=df, target=target, session_id=7, fold_shuffle=True,
                ignore_features=ignored_features_initial, verbose=False, fix_imbalance=True)  # Ajuste de clases desbalanceadas

    # Entrenar modelo inicial
    xgb_model = create_model('xgboost')

    # Obtener importancias originales
    initial_features = get_config('X').columns.tolist()
    initial_importances = xgb_model.feature_importances_
    original_importance_dict = dict(zip(initial_features, initial_importances))

    # Añadir cero para características ya ignoradas
    for feat in ignored_features_initial:
        original_importance_dict[feat] = 0

    # Preparar listas para almacenar resultados
    results = []
    ignored_features = ignored_features_initial.copy()
    accuracy_list = []
    recall_list = []
    f1_list = []
    precision_list = []

    # Función para evaluar el modelo
    def evaluate_model(predictions):
        try:
            y_true = predictions[target]
            y_pred = predictions['prediction_label']  # Usar 'Label' en lugar de 'prediction_label'
            acc = accuracy_score(y_true, y_pred)
            rec = recall_score(y_true, y_pred, average='weighted')
            f1 = f1_score(y_true, y_pred, average='weighted')
            prec = precision_score(y_true, y_pred, average='weighted')
            return acc, rec, f1, prec
        except Exception as e:
            print(f"Error en evaluación: {str(e)}")
            return 0.0, 0.0, 0.0, 0.0

    iteration = 0
    while True:
        current_features = get_config('X').columns.tolist()
        predictions = predict_model(xgb_model)
        accuracy, recall, f1, precision = evaluate_model(predictions)

        # Almacena las métricas en las listas
        accuracy_list.append(accuracy)
        recall_list.append(recall)
        f1_list.append(f1)
        precision_list.append(precision)

        # Obtener importancias actuales
        current_importances = xgb_model.feature_importances_
        current_importance_dict = dict(zip(current_features, current_importances))

        # Crear diccionario para esta iteración
        iteration_dict = {
            'Model_Iteration': iteration,
            'Removed_Feature': 'None' if iteration == 0 else removed_feature,
            'Original_Importance': 0 if iteration == 0 else original_importance_dict[removed_feature],
            'Features_Used': len(current_features),
            'Features_Ignored': len(ignored_features),
            'Accuracy': accuracy,
            'Recall': recall,
            'F1_Score': f1,
            'Precision': precision
        }

        # Añadir importancias actuales para todas las características originales
        for feature in all_features:
            importance_key = f'Importance_{feature}'
            if feature in current_importance_dict:
                iteration_dict[importance_key] = current_importance_dict[feature]
            else:
                iteration_dict[importance_key] = np.nan

        results.append(iteration_dict)

        if len(current_features) <= 1:
            break

        # Encontrar la próxima característica a eliminar (la de menor importancia original)
        available_features = set(current_features) - set(ignored_features)
        if not available_features:
            break

        removed_feature = min(available_features, key=lambda x: original_importance_dict.get(x, float('inf')))
        ignored_features.append(removed_feature)

        # Reentrenar modelo sin reiniciar el setup
        clf = setup(data=df, target=target, session_id=7, fold_shuffle=True,
                   ignore_features=ignored_features, verbose=False, fix_imbalance=True)  # Mantener ajuste para clases desbalanceadas
        xgb_model = create_model('xgboost')

        iteration += 1

    # Crear DataFrame final
    results_df = pd.DataFrame(results)

    # Añadir las listas de métricas al DataFrame
    results_df['Accuracy'] = accuracy_list
    results_df['Recall'] = recall_list
    results_df['F1_Score'] = f1_list
    results_df['Precision'] = precision_list

    # Reordenar columnas
    importance_cols = [col for col in results_df.columns if col.startswith('Importance_')]
    base_cols = ['Model_Iteration', 'Removed_Feature', 'Original_Importance',
                 'Features_Used', 'Features_Ignored']
    final_cols = base_cols + importance_cols + ['Accuracy', 'Recall', 'F1_Score', 'Precision']

    results_df = results_df[final_cols]
    return results_df

# Ejecutar el proceso
detailed_results = create_detailed_selection_process(df)

# Guardar resultados
detailed_results.to_csv('detailed_feature_selection_results.csv', index=False)

# Mostrar primeras filas
print(detailed_results.head())

# Mostrar estadísticas básicas
print("\nEstadísticas de métricas:")
print(detailed_results[['Accuracy', 'Recall', 'F1_Score', 'Precision']].describe())

# Encontrar el mejor modelo según F1-Score
best_model = detailed_results.loc[detailed_results['F1_Score'].idxmax()]
print("\nMejor modelo:")
print(f"Iteración: {best_model['Model_Iteration']}")
print(f"Características usadas: {best_model['Features_Used']}")
print(f"F1-Score: {best_model['F1_Score']:.4f}")

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

   Model_Iteration Removed_Feature  Original_Importance  Features_Used  \
0                0            None             0.000000             36   
1                1           Speed             0.000000             35   
2                2         Jumping             0.000000             34   
3                3             Age             0.000000             33   
4                4       Dribbling             0.001207             32   

   Features_Ignored  Importance_Name  Importance_Nationality  \
0                 4              NaN                     NaN   
1                 5              NaN                     NaN   
2                 6              NaN                     NaN   
3                 7              NaN                     NaN   
4                 8              NaN                     NaN   

   Importance_National_Position  Importance_Club_Position  Importance_Height  \
0                           NaN                  0.015243           0.009054   
1         

In [85]:
detailed_results

Model_Iteration    Removed_Feature  Original_Importance  Features_Used  \
0                 0               None             0.000000             36   
1                 1              Speed             0.000000             35   
2                 2            Jumping             0.000000             34   
3                 3                Age             0.000000             33   
4                 4          Dribbling             0.001207             32   
5                 5       Acceleration             0.002554             31   
6                 6          Work_Rate             0.004630             30   
7                 7          Finishing             0.005623             29   
8                 8  Freekick_Accuracy             0.005857             28   
9                 9            Agility             0.006065             27   
10               10             Vision             0.007254             26   
11               11         Aggression             0.007727             25   
12               12             Height             0.009054             24   
13               13            Volleys             0.009757             23   
14               14          Penalties             0.010031             22   
15               15            Stamina             0.010354             21   
16               16            Balance             0.012530             20   
17               17            Marking             0.014065             19   
18               18           Crossing             0.015220             18   
19               19      Club_Position             0.015243             17   
20               20         Long_Shots             0.015473             16   
21               21      Interceptions             0.015622             15   
22               22             Weight             0.015637             14   
23               23         Shot_Power             0.016161             13   
24               24    Standing_Tackle             0.016406             12   
25               25     Sliding_Tackle             0.017585             11   
26               26        Skill_Moves             0.022464             10   
27               27              Curve             0.024572              9   
28               28     Preffered_Foot             0.025608              8   
29               29          Weak_foot             0.027153              7   
30               30          Long_Pass             0.033277              6   
31               31       Ball_Control             0.043501              5   
32               32          Reactions             0.044912              4   
33               33            Heading             0.046161              3   
34               34          Composure             0.065561              2   
35               35         Short_Pass             0.070652              1   

    Features_Ignored  Importance_Name  Importance_Nationality  \
0                  4              NaN                     NaN   
1                  5              NaN                     NaN   
2                  6              NaN                     NaN   
3                  7              NaN                     NaN   
4                  8              NaN                     NaN   
5                  9              NaN                     NaN   
6                 10              NaN                     NaN   
7                 11              NaN                     NaN   
8                 12              NaN                     NaN   
9                 13              NaN                     NaN   
10                14              NaN                     NaN   
11                15              NaN                     NaN   
12                16              NaN                     NaN   
13                17              NaN                     NaN   
14                18              NaN                     NaN   
15                19              NaN                     NaN   
16          

aaa

In [ ]:
omitir=['Name', 'Nationality', 'National_Position', 'Club_Position', 'Standing_Tackle',
 'Reactions', 'Aggression', 'Interceptions', 'Skill_Moves', 'Crossing', 'Ball_Control', 'Short_Pass', 'Dribbling',
 'Speed', 'Stamina', 'Strength', 'Acceleration', 'Balance', 'Jumping', 'Heading', 'Sliding_Tackle',
 'Vision', 'Long_Shots', 'Curve', 'Composure', 'Long_Pass', 'Agility',
 'Shot_Power', 'Finishing', 'Freekick_Accuracy', 'Penalties', 'Volleys', 'label_pos', 'Marking','Height']

clf = setup(data=df, target='label', session_id=7, fold_shuffle=True,
             ignore_features=omitir)

xgb_model2 = create_model('xgboost')
evaluate_model(xgb_model2)

5. RESPONDER

### 3.3 Calibración Probabilistica [6 puntos]

<center>
<img src='https://media2.giphy.com/media/l2Je4Ku0Cx292KWv6/200w.gif?cid=6c09b952y0sihtq9tb6sz8j2023x3zxxp3qx1ocgonkpkblj&ep=v1_gifs_search&rid=200w.gif&ct=g' width=400 />

Para lograr modelos más modulares, se recomienda realizar una calibración del modelo entrenado anteriormente, con el objetivo de obtener salidas que reflejen mayor modularidad.

1. Se solicita que utilice un método de calibración que asegure que las probabilidades generadas incrementen de manera monótona. Una métrica ampliamente utilizada para evaluar la precisión de la calibración de un modelo es el Brier Score. Calcule el Brier Score para el modelo tanto antes como después de la calibración. Esto le permitirá realizar una comparación cuantitativa y determinar si la calibración ha mejorado el rendimiento del modelo. Para más información sobre el Brier Score, puede consultar el siguiente enlace: [Scikit-Learn - Brier Score Loss](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.brier_score_loss.html). [3 puntos]

2. Tras la calibración, examine y comente los resultados obtenidos. A su análisis añada una comparación visual de las ideales versus las salidas del modelo original (sin calibrar) y del modelo calibrado. [3 puntos]

**Respuesta**